### ISSUE TITLE
Support for multiple named collections

### ISSUE THREAD

**Issue by blahah** [slidewinder/slidewinder#11]
_From @Ward9250 on November 29, 2015 1:3_

Making the preentation for cambs it became clear support for using multiple collections was required.... so I did it.

Now you can do the following:

```
node bin/cmdline.js \
    -c a:~/Desktop/examples,b:~/Desktop/collection2 \
    -s a\(code,data,list\),b\(features\),a\(code_highlighted\) \
    -o ~/Desktop/mytestpres
    -a meeeeee
    -t multicollections
```

Notice the arguments passed to the -c and -s flag are changed.

For the -c flag, you give a name for the collection along with the path, so for the collection in directory `~/Desktop/examples`, the name `a` is provided. These names are totally transient, they don't get saved in slides or collection directories or anything like that. Then in the -s flag, you specify the slides you want from the collections in order. The syntax reads left to right, and dictates the flow of the presentation: the first slide will be `code` from collection `a`, followed by `data` and then `list` from collection `a`. Then the fourth slide will be `features` from collection `b`, followed by `code_highlighted` from collection `a`. The parens in -s had to be escaped 'cause bash.

I also formed some classes from the functions and datastructures used in slidewinder to accompany the framework class. Namely, the `SlideCollection`, and `SlideDeck` classes. I think it makes sense, given that they are two datastructures central to slidewinder, and also central concepts - a deck is a ordered set of slides presented, a collection is more like an archive of slides and associated media.

_Copied from original issue: Blahah/slidewinder/pull/11_

**Comment by TransGirlCodes** [comment]
This was what drove the need to be able to make slides using a yaml specification file.

**Comment by blahah** [comment]
Indeed - this was actually a PR from you and it was merged. Confused by the issue transfer!
