### ISSUE TITLE
slide identifiers

### ISSUE THREAD

**Issue by blahah** [slidewinder/slidewinder#25]
we need some way to identify a slide uniquely.

this need arises when a user wants to trace back where a modified slide came from. Ideally there's a unique identifier, which could a URI so the original slide can be visited.

@Ward9250 your previous ideas about databases seem relevant now. I'm wondering if we should load things into a db but allow ingesting / writing out to a simple markdown.

**Comment by TransGirlCodes** [comment]
I wonder if this is something we can do with just filesystem, in a way git does, with folders in a tree structure with custom hash numbers / custom identifies for names. I've wondered if versions of collections might be partly solved by having collections also git repos.
